<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crafts N Cloud technology </title>
    <link rel="stylesheet" href="templatemo-prism-flux.css">
<!-- 

TemplateMo 600 Prism Flux

https://templatemo.com/tm-600-prism-flux

-->
</head>
<body>
<?php include "header.php"; ?>


    <!-- NEW: Prism Philosophy Section (About) 
    <section class="philosophy-section" id="about">-->
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                Turning Ideas <br>Into Reality
            </h2>
            
            <p class="philosophy-subheading">
                At Crafts n Cloud, we help turn complex ideas into clear, practical solutions. 
                By combining smart technology with thoughtful design,
                we create digital experiences that actually work for people. 
                Every project is a new opportunity to build something meaningful, simple, and impactful.
            </p>
            
            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">💎</div>
                    <h3 class="pillar-title">Innovation</h3>
                    <p class="pillar-description">
                    We explore new ideas and smarter ways of working to create designs that truly stand out. 
                    By thinking differently and using fresh approaches, 
                    we help push your brand forward and deliver creative results that feel modern, useful, and inspiring.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">🔬</div>
                    <h3 class="pillar-title">Precision</h3>
                    <p class="pillar-description">
                    We pay close attention to every detail — from clean design to smooth performance.
                     Every element is carefully built to look great,
                     work flawlessly, and deliver a seamless experience users can trust.                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">∞</div>
                    <h3 class="pillar-title">Evolution</h3>
                    <p class="pillar-description">
                    We keep learning, improving, and adapting to what’s next. 
                    By staying up to date with new trends and technologies, 
                    we build smart solutions that work today and remain valuable for the future.
                    </p>
                </div>
            </div>
              <!--  at <a href="https://timermo.com" rel="nofollow" target="_blank">TimerMo</a>." 
              reffernce to have perticular text into link--> 
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

<?php include "footer.php"; ?>

<script src="templatemo-prism-scripts.js"></script>
</body>
</html>