<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crafts N Cloud technology </title>
    <link rel="stylesheet" href="templatemo-prism-flux.css">

</head>
<body>
<?php include "header.php"; ?>


    <!-- Hero Section with 3D Carousel 
    <section class="hero" id="home">-->


             <div class="carousel-container">
            <div class="carousel" id="carousel">
          <!--  Carousel items will be generated by JavaScript  -->
            </div>
            
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
            
            <div class="carousel-indicators" id="indicators">
            <!--   Indicators will be generated by JavaScript-->
            </div>
        </div>
    </section>

    <!-- NEW: Prism Philosophy Section (About) 
    <section class="philosophy-section" id="about">-->
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                Turning Ideas <br>Into Reality
            </h2>
            
            <p class="philosophy-subheading">
                At Crafts n Cloud, we help turn complex ideas into clear, practical solutions. 
                By combining smart technology with thoughtful design,
                we create digital experiences that actually work for people. 
                Every project is a new opportunity to build something meaningful, simple, and impactful.
            </p>
            
            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">💎</div>
                    <h3 class="pillar-title">Innovation</h3>
                    <p class="pillar-description">
                    We explore new ideas and smarter ways of working to create designs that truly stand out. 
                    By thinking differently and using fresh approaches, 
                    we help push your brand forward and deliver creative results that feel modern, useful, and inspiring.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">🔬</div>
                    <h3 class="pillar-title">Precision</h3>
                    <p class="pillar-description">
                    We pay close attention to every detail — from clean design to smooth performance.
                     Every element is carefully built to look great,
                     work flawlessly, and deliver a seamless experience users can trust.                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">∞</div>
                    <h3 class="pillar-title">Evolution</h3>
                    <p class="pillar-description">
                    We keep learning, improving, and adapting to what’s next. 
                    By staying up to date with new trends and technologies, 
                    we build smart solutions that work today and remain valuable for the future.
                    </p>
                </div>
            </div>
              <!--  at <a href="https://timermo.com" rel="nofollow" target="_blank">TimerMo</a>." 
              reffernce to have perticular text into link--> 
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Stats Section with Content 
    <section class="stats-section" id="stats">-->
        <div class="section-header">
            <h2 class="section-title">Performance Metrics</h2>
            <p class="section-subtitle">Real-time analytics and achievements powered by cutting-edge technology</p>
        </div>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon">🚀</div>
                <div class="stat-number" data-target="150">5</div>
                <div class="stat-label">Projects Completed</div>
                <p class="stat-description">Successfully delivered enterprise-level solutions across multiple industries with 100% on-time completion rate.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">⚡</div>
                <div class="stat-number" data-target="99">99%</div>
                <div class="stat-label">Client Satisfaction %</div>
                <p class="stat-description">Maintaining excellence through continuous feedback loops and agile development methodologies.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">🏆</div>
                <div class="stat-number" data-target="25">10</div>
                <div class="stat-label">Industry Awards</div>
                <p class="stat-description">Recognized globally for innovation in digital transformation and technological advancement.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">💎</div>
                <div class="stat-number" data-target="500">200</div>
                <div class="stat-label">Code Commits Daily</div>
                <p class="stat-description">Continuous integration and deployment with automated testing ensuring maximum code quality.</p>
            </div>
        </div>
    </section>

    <!-- Enhanced Skills Section - Technical Arsenal 
    <section class="skills-section" id="skills">-->
        <div class="skills-container">
            <div class="section-header">
                <h2 class="section-title">Technical Arsenal</h2>
                <p class="section-subtitle">Mastery of cutting-edge technologies and frameworks</p>
            </div>
            
            <div class="skill-categories">
                <div class="category-tab active" data-category="all">All Skills</div>
                <div class="category-tab" data-category="frontend">Frontend</div>
                <div class="category-tab" data-category="backend">Backend</div>
                <div class="category-tab" data-category="cloud">Cloud & DevOps</div>
                <div class="category-tab" data-category="emerging">Emerging Tech</div>
            </div>

            <div class="skills-hexagon-grid" id="skillsGrid">
                <!-- Hexagonal skill items will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Contact Section 
    <section class="contact-section" id="contact">-->
        <div class="section-header">
            <h2 class="section-title">Initialize Connection</h2>
            <p class="section-subtitle">Ready to transform your vision into reality? Let's connect.</p>
        </div>
        
        <div class="contact-container">
            <div class="contact-info">
                <a href="https://www.google.com/maps/place/Anandnagar,+Bhopal,+Madhya+Pradesh+462022/@23.2512561,77.4760511,2131m/data=!3m2!1e3!4b1!4m6!3m5!1s0x397c41e40648af0d:0xb256191a4c992275!8m2!3d23.2520103!4d77.4856647!16s%2Fg%2F1jkyjgkld?entry=ttu&g_ep=EgoyMDI2MDIwNC4wIKXMDSoKLDEwMDc5MjA3M0gBUAM%3D" target="_blank" class="info-item">
                    <div class="info-icon">📍</div>
                    <div class="info-text">
                        <h4>Location</h4>
                        <p>Bhopal</p>
                    </div>
                </a>
                
                <a href="mailto:hello@prismflux.io" class="info-item">
                    <div class="info-icon">📧</div>
                    <div class="info-text">
                        <h4>Email</h4>
                        <p>Support@craftsncloude.in</p>
                    </div>
                </a>
                
                <a href="tel:+15551234567" class="info-item">
                    <div class="info-icon">📱</div>
                    <div class="info-text">
                        <h4>Phone</h4>
                        <p>+91-10101010</p>
                    </div>
                </a>
                
                <a href="" target="_blank" class="info-item">
                    <div class="info-icon">📅</div>
                    <div class="info-text">
                        <h4>Schedule Meeting</h4>
                        <p>Book a consultation</p>
                    </div>
                </a>
            </div>
            
            <?php
if(isset($_GET['status'])) {
    if($_GET['status'] == "success") {
        echo "
        <script>
            alert('Message sent successfully!');
            window.history.replaceState({}, document.title, window.location.pathname);
        </script>
        ";
    } elseif($_GET['status'] == "error") {
        echo "
        <script>
            alert('Something went wrong. Try again.');
            window.history.replaceState({}, document.title, window.location.pathname);
        </script>
        ";
    }
}
?>
            
            <form class="contact-form" id="contactForm" method="POST"
                                                action="contact_process.php">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" required>
                </div>
                
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" required>
                </div>
                
                <div class="form-group">
                    <label for="subject">Subject</label>
                    <input type="text" id="subject" name="subject" required>
                </div>
                <div class="form-group">
                    <label for="subject">Services</label>
                    <input type="text" id="services" name="services" required>
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea id="message" name="message" required></textarea>
                </div>
                
                <button type="submit" class="submit-btn">Transmit Message</button>
            </form>
        </div>
    </section>



<?php include "footer.php"; ?>
<script src="templatemo-prism-scripts.js"></script>
</body>
</html>